name: gdutils

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  go-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up GoLang
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Check code standards
        run: test -z $(gofmt -l .)

  go-vet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up GoLang
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Look for suspicious code
        run: go vet

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up GoLang
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Run unit tests
        run: go test -race -coverprofile=c.out ./...